// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ConfirmDialog'](arg1, arg2);
}

export function DeleteDocument(arg1) {
  return window['go']['avnacio']['IOManager']['DeleteDocument'](arg1);
}

export function DeletePages(arg1) {
  return window['go']['avnacio']['IOManager']['DeletePages'](arg1);
}

export function DuplicatePages(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['DuplicatePages'](arg1, arg2);
}

export function ExportFile(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ExportFile'](arg1, arg2);
}

export function ExportPng(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ExportPng'](arg1, arg2);
}

export function ExportTextFile(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ExportTextFile'](arg1, arg2);
}

export function ListDocuments() {
  return window['go']['avnacio']['IOManager']['ListDocuments']();
}

export function ReadDocumentRecord(arg1) {
  return window['go']['avnacio']['IOManager']['ReadDocumentRecord'](arg1);
}

export function ReadPages(arg1) {
  return window['go']['avnacio']['IOManager']['ReadPages'](arg1);
}

export function ReadVectorBoardDocs(arg1) {
  return window['go']['avnacio']['IOManager']['ReadVectorBoardDocs'](arg1);
}

export function ReadVectorBoards(arg1) {
  return window['go']['avnacio']['IOManager']['ReadVectorBoards'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['Startup'](arg1, arg2);
}

export function WriteDocumentRecord(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['WriteDocumentRecord'](arg1, arg2);
}

export function WritePages(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['WritePages'](arg1, arg2);
}

export function WriteVectorBoardDocs(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['WriteVectorBoardDocs'](arg1, arg2);
}

export function WriteVectorBoards(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['WriteVectorBoards'](arg1, arg2);
}
