// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function DeleteDocument(arg1:string):Promise<void>;

export function DeletePages(arg1:string):Promise<void>;

export function DuplicatePages(arg1:string,arg2:string):Promise<void>;

export function ExportFile(arg1:string,arg2:Array<number>):Promise<void>;

export function ExportPng(arg1:string,arg2:string):Promise<void>;

export function ExportTextFile(arg1:string,arg2:string):Promise<void>;

export function ListDocuments():Promise<string>;

export function ReadDocumentRecord(arg1:string):Promise<string>;

export function ReadPages(arg1:string):Promise<string>;

export function ReadVectorBoardDocs(arg1:string):Promise<string>;

export function ReadVectorBoards(arg1:string):Promise<string>;

export function Startup(arg1:context.Context,arg2:string):Promise<void>;

export function WriteDocumentRecord(arg1:string,arg2:string):Promise<void>;

export function WritePages(arg1:string,arg2:string):Promise<void>;

export function WriteVectorBoardDocs(arg1:string,arg2:string):Promise<void>;

export function WriteVectorBoards(arg1:string,arg2:string):Promise<void>;
