// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {context} from '../models';
import {avnacconfig} from '../models';

export function GetMCPInfo():Promise<mcp.MCPState>;

export function RegenerateToken():Promise<void>;

export function RegisterPrompts():Promise<void>;

export function RegisterTools(arg1:context.Context):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function StartHTTP(arg1:mcp.HTTPOptions):Promise<void>;

export function Stop(arg1:context.Context):Promise<void>;

export function SubmitResponse(arg1:string,arg2:any):Promise<void>;

export function UpdateConfig(arg1:avnacconfig.AppConfig):Promise<void>;
